#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ -w "/config/crontabs/abc" ] 
then
   printf "Auto Cron: Checking...\n"
   php /etc/s6-overlay/s6-rc.d/init-stravastat-cron-config/auto-cron-config.php
   crontab -u "abc" "/config/crontabs/abc"
else
   printf "/config/crontabs/abc is not writeable! Skipping Auto Cron parsing\n"
fi