#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config \
        /var/www \
        /run \
        /var/lib/nginx \
        /var/log/nginx

    touch /run/php-fpm.sock
    lsiown abc:abc /run/php-fpm.sock
fi