#!/usr/bin/with-contenv bash
# shellcheck shell=bash

touch /tmp/php-fpm.sock

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config \
        /var/www \
        /var/lib/nginx \
        /var/log/nginx

    lsiown abc:abc /tmp/php-fpm.sock
fi